spring:
  #activeMQ
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    pool:
      enabled: true
    packages:
      trust-all: true   # 如果使用ObjectMessage传输对象，必须要加上这个信任包，否则会报ClassNotFound异常
  jms:
    pub-sub-domain: true  # 启动主题消息
    #web界面是9200，但是和java交互是9300，es
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: "zhang"
    database: 0
    jedis:
      pool:
        max-idle: 6
        max-active: 32
        max-wait: 100
        min-idle: 4

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/daboluo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
      # 初始化时建立物理连接连接的个数
    initialSize: 5
      # 最小连接池数量
    minIdle: 5
    # 最大连接池数量
    maxActive: 20
      # 获取连接时最大等待时间(ms)，即60s
    maxWait: 60000
      # 1.Destroy线程会检测连接的间隔时间；2.testWhileIdle的判断依据
    timeBetweenEvictionRunsMillis: 60000
      # 最小生存时间ms
    minEvictableIdleTimeMillis: 600000
    maxEvictableIdleTimeMillis: 10000000
      # 用来检测连接是否有效的sql
    validationQuery: SELECT 1 FROM DUAL
      # 申请连接时执行validationQuery检测连接是否有效，启用会降低性能
    testOnBorrow: false
      # 归还连接时执行validationQuery检测连接是否有效，启用会降低性能
    testOnReturn: false
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，
      # 执行validationQuery检测连接是否有效，不会降低性能
    testWhileIdle: true
      # 是否缓存preparedStatement，mysql建议关闭
    poolPreparedStatements: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    #配置日志输出
    filter:
      slf4j:
        enabled: true
        statement-create-after-log-enabled: false
        statement-close-after-log-enabled: false
        result-set-open-after-log-enabled: false
        result-set-close-after-log-enabled: false
    #关闭模板引擎缓存
  thymeleaf:
    cache: false


logging:
  config: classpath:log4j2.xml