# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8085
  #servlet:
    #context-path: /xx


spring:
  # 环境 sit:集成测试环境|pre:预生产环境|dev:生成环境
  profiles:
    active: @spring.active@
  mvc:
    static-path-pattern: /static/**
    # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
      #热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
# Mybatis配置
mybatis:
  configLocation: classpath:mybatis.xml
  mapper-locations: classpath*:marco/zlc/dabl/modules/system/mapper/*.xml
  type-aliases-package: marco.zlc.dabl.modules.system.entity